github-workflows: Use Python 3.13 for ansible-core-2.19.x
Fixes:
  RuntimeError: Python 3.14 requires ansible-core version >= 2.20.0, and
  we found 2.19.3.