molecule: Avoid regression with ansible-core 2.17.0 and Rocky 8
[...]
File "/tmp/ansible_ansible.legacy.dnf_payload_rj2o7nel/ansible_ansible.legacy.dnf_payload.zip/ansible/module_utils/basic.py", line 5
SyntaxError: future feature annotations is not defined